"""Frozen SQLAlchemy schema used exclusively by Alembic revision 0001."""

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB

__all__ = ["metadata"]

metadata = MetaData()
_JSON_TYPE = JSON().with_variant(JSONB, "postgresql")

Table(
    "sources",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("language", String(8), nullable=False),
    Column("provider", String(32), nullable=False),
    Column("provider_id", String(64), nullable=False),
    Column("url", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("channel", Text, nullable=True),
    Column("uploader_url", Text, nullable=True),
    Column("duration_s", Float, nullable=True),
    Column("topic", String(64), nullable=True),
    Column("license_name", String(128), nullable=True),
    Column("upload_date", String(16), nullable=True),
    Column("description", Text, nullable=True),
    Column("audio_key", Text, nullable=True),
    Column("audio_bytes", Integer, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("provider", "provider_id", name="uq_source_provider"),
    Index("ix_sources_language", "language"),
    Index("ix_sources_topic", "topic"),
)

Table(
    "transcripts",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("source_id", Integer, ForeignKey("sources.id", ondelete="CASCADE"), nullable=False),
    Column("language", String(8), nullable=False),
    Column("asr_backend", String(32), nullable=False),
    Column("asr_model", String(64), nullable=False),
    Column("text", Text, nullable=False),
    Column("word_count", Integer, nullable=False),
    Column("duration_s", Float, nullable=False),
    Column("raw_key", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

Table(
    "segments",
    metadata,
    Column("id", Integer, primary_key=True),
    Column(
        "transcript_id",
        Integer,
        ForeignKey("transcripts.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("idx", Integer, nullable=False),
    Column("start_s", Float, nullable=False),
    Column("end_s", Float, nullable=False),
    Column("text", Text, nullable=False),
    Column("words_json", _JSON_TYPE, nullable=True),
    Column("avg_logprob", Float, nullable=True),
    Column("no_speech_prob", Float, nullable=True),
    Index("ix_segment_transcript_idx", "transcript_id", "idx"),
)

Table(
    "lessons",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("source_id", Integer, ForeignKey("sources.id", ondelete="CASCADE"), nullable=False),
    Column(
        "transcript_id",
        Integer,
        ForeignKey("transcripts.id", ondelete="SET NULL"),
        nullable=True,
    ),
    Column("language", String(8), nullable=False),
    Column("skill", String(16), nullable=False),
    Column("title", Text, nullable=False),
    Column("topic", String(64), nullable=True),
    Column("cefr", String(4), nullable=True),
    Column("difficulty_score", Float, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_lessons_language", "language"),
    Index("ix_lessons_skill", "skill"),
)

Table(
    "listening_units",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("lesson_id", Integer, ForeignKey("lessons.id", ondelete="CASCADE"), nullable=False),
    Column("idx", Integer, nullable=False),
    Column("start_s", Float, nullable=False),
    Column("end_s", Float, nullable=False),
    Column("text", Text, nullable=False),
    Column("words_json", _JSON_TYPE, nullable=True),
    Column("clip_key", Text, nullable=True),
    Column("wpm", Float, nullable=True),
    Column("cefr", String(4), nullable=True),
    Column("difficulty_score", Float, nullable=True),
    Column("difficulty_detail", _JSON_TYPE, nullable=False),
    Column("gist", Text, nullable=True),
    Index("ix_unit_lesson_idx", "lesson_id", "idx"),
)

Table(
    "exercises",
    metadata,
    Column("id", Integer, primary_key=True),
    Column(
        "unit_id",
        Integer,
        ForeignKey("listening_units.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("skill", String(16), nullable=False),
    Column("kind", String(24), nullable=False),
    Column("order_idx", Integer, nullable=False),
    Column("prompt", Text, nullable=False),
    Column("payload", _JSON_TYPE, nullable=False),
    Column("answer", _JSON_TYPE, nullable=False),
    Column("explanation", Text, nullable=True),
    Column("audio_start_s", Float, nullable=True),
    Column("audio_end_s", Float, nullable=True),
    Column("cefr", String(4), nullable=True),
    Column("generator", String(32), nullable=False),
    Column("review_state", String(16), nullable=False),
    Column("reviewed_by", String(64), nullable=True),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_exercise_unit_order", "unit_id", "order_idx"),
    Index("ix_exercises_kind", "kind"),
    Index("ix_exercises_review_state", "review_state"),
    Index("ix_exercises_skill", "skill"),
)

Table(
    "attempts",
    metadata,
    Column("id", Integer, primary_key=True),
    Column(
        "exercise_id",
        Integer,
        ForeignKey("exercises.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("learner_key", String(64), nullable=False),
    Column("user_id", String(36), nullable=True),
    Column("response", _JSON_TYPE, nullable=False),
    Column("is_correct", Boolean, nullable=False),
    Column("score", Float, nullable=False),
    Column("feedback", _JSON_TYPE, nullable=False),
    Column("replays", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_attempt_learner_created", "learner_key", "created_at"),
    Index("ix_attempts_learner_key", "learner_key"),
    Index("ix_attempts_user_id", "user_id"),
)

Table(
    "vocab_items",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("learner_key", String(64), nullable=False),
    Column("user_id", String(36), nullable=True),
    Column("language", String(8), nullable=False),
    Column("headword", String(128), nullable=False),
    Column("gloss_en", Text, nullable=True),
    Column("example", Text, nullable=True),
    Column("zipf", Float, nullable=True),
    Column(
        "unit_id",
        Integer,
        ForeignKey("listening_units.id", ondelete="SET NULL"),
        nullable=True,
    ),
    Column("reps", Integer, nullable=False),
    Column("lapses", Integer, nullable=False),
    Column("ease", Float, nullable=False),
    Column("interval_days", Float, nullable=False),
    Column("due_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("learner_key", "language", "headword", name="uq_vocab_learner_word"),
    Index("ix_vocab_items_language", "language"),
    Index("ix_vocab_items_learner_key", "learner_key"),
    Index("ix_vocab_items_user_id", "user_id"),
)

Table(
    "expressions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column(
        "unit_id",
        Integer,
        ForeignKey("listening_units.id", ondelete="CASCADE"),
        nullable=True,
    ),
    Column("language", String(8), nullable=False),
    Column("surface", Text, nullable=False),
    Column("canonical", Text, nullable=False),
    Column("lemma_key", String(255), nullable=False),
    Column("kind", String(24), nullable=False),
    Column("gloss_en", Text, nullable=False),
    Column("literal_en", Text, nullable=True),
    Column("note", Text, nullable=True),
    Column("char_start", Integer, nullable=False),
    Column("char_end", Integer, nullable=False),
    Column("component_spans", _JSON_TYPE, nullable=False),
    Column("confidence", Float, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_expr_unit_span", "unit_id", "char_start", "char_end"),
    Index("ix_expr_lemma_key", "language", "lemma_key"),
    Index("ix_expressions_language", "language"),
)

Table(
    "sentence_analyses",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("language", String(8), nullable=False),
    Column("text_key", String(64), nullable=False),
    Column("text", Text, nullable=False),
    Column("translation_en", Text, nullable=False),
    Column("register", String(24), nullable=True),
    Column("structures", _JSON_TYPE, nullable=False),
    Column("practices", _JSON_TYPE, nullable=False),
    Column("notes", Text, nullable=True),
    Column("hits", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("language", "text_key", name="uq_sentence_lookup"),
    Index("ix_sentence_analyses_language", "language"),
)

Table(
    "gloss_cache",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("language", String(8), nullable=False),
    Column("surface_key", String(255), nullable=False),
    Column("context_key", String(64), nullable=False),
    Column("surface", Text, nullable=False),
    Column("lemma", String(128), nullable=True),
    Column("pos", String(32), nullable=True),
    Column("gloss_en", Text, nullable=False),
    Column("senses", _JSON_TYPE, nullable=False),
    Column("note", Text, nullable=True),
    Column("zipf", Float, nullable=True),
    Column("hits", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("language", "surface_key", "context_key", name="uq_gloss_lookup"),
    Index("ix_gloss_cache_language", "language"),
)
