"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: bootstrap

Built from the model metadata rather than autogenerated DDL, deliberately.

Autogenerating this against the local SQLite database renders `sa.JSON()` for the eleven
JSON columns, which on Postgres creates `json` — text storage that cannot be usefully
indexed — instead of the `jsonb` the models ask for. Going through `metadata.create_all`
lets SQLAlchemy render each column for the dialect it is actually connecting to, so the
same revision produces jsonb on Supabase and json on a local SQLite file.

Every migration after this one is a normal autogenerate against Postgres.
"""

from __future__ import annotations

from alembic import op

from app.models import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
