"""drill mode question bank

Revision ID: 0004_drill_mode
Revises: 0003_accounts

Four tables for imported exam material. Purely additive — nothing study mode reads or
writes is touched.

They sit beside `exercises` rather than inside it. An exam item has no source video, no
ASR pass and no timeline, so reusing `exercises` would mean either inventing a source, a
lesson and a unit for every question, or relaxing `exercises.unit_id` to nullable and
auditing every existing access to `exercise.unit` for a case study mode never produces.
The second puts the risk on the module that gains nothing from the change. Separate
tables are also the better fit: an exam item's shape is fixed and known, so it can be
columns that SQL filters and samples on rather than JSON inside a generic payload.

The two modes stay joinable where it counts — `drill_attempts` carries the same
`learner_key` / `user_id` pair as `attempts`, so one progress view is a UNION away.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004_drill_mode'
down_revision: Union[str, Sequence[str], None] = '0003_accounts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drill_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=16), nullable=False),
    sa.Column('skill', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=4), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam', 'name', name='uq_drill_collection_name')
    )
    op.create_index('ix_drill_collection_skill', 'drill_collections', ['exam', 'skill'], unique=False)
    op.create_index(op.f('ix_drill_collections_exam'), 'drill_collections', ['exam'], unique=False)
    op.create_index(op.f('ix_drill_collections_skill'), 'drill_collections', ['skill'], unique=False)
    op.create_table('drill_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=4), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('time_limit_s', sa.Integer(), nullable=True),
    sa.Column('document', sa.Text(), nullable=False),
    sa.Column('document_corrected', sa.Text(), nullable=True),
    sa.Column('document_zh', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('model_answer_fr', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(length=4), nullable=True),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('audio_key', sa.Text(), nullable=True),
    sa.Column('canonical', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('corrections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind <> 'mcq' OR answer IS NOT NULL", name='ck_drill_mcq_has_answer'),
    sa.ForeignKeyConstraint(['collection_id'], ['drill_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of'], ['drill_questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam', 'external_id', name='uq_drill_question_external')
    )
    op.create_index('ix_drill_collection_seq', 'drill_questions', ['collection_id', 'seq'], unique=False)
    op.create_index(op.f('ix_drill_questions_canonical'), 'drill_questions', ['canonical'], unique=False)
    op.create_index(op.f('ix_drill_questions_exam'), 'drill_questions', ['exam'], unique=False)
    op.create_index(op.f('ix_drill_questions_kind'), 'drill_questions', ['kind'], unique=False)
    op.create_index(op.f('ix_drill_questions_level'), 'drill_questions', ['level'], unique=False)
    op.create_index(op.f('ix_drill_questions_skill'), 'drill_questions', ['skill'], unique=False)
    op.create_index('ix_drill_sample', 'drill_questions', ['skill', 'level', 'canonical'], unique=False)
    op.create_table('drill_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('learner_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('selected', sa.String(length=4), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['drill_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drill_attempt_learner', 'drill_attempts', ['learner_key', 'created_at'], unique=False)
    op.create_index('ix_drill_attempt_question', 'drill_attempts', ['question_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_drill_attempts_learner_key'), 'drill_attempts', ['learner_key'], unique=False)
    op.create_index(op.f('ix_drill_attempts_user_id'), 'drill_attempts', ['user_id'], unique=False)
    op.create_table('drill_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=4), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_corrected', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['drill_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'label', name='uq_drill_option_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drill_options')
    op.drop_index(op.f('ix_drill_attempts_user_id'), table_name='drill_attempts')
    op.drop_index(op.f('ix_drill_attempts_learner_key'), table_name='drill_attempts')
    op.drop_index('ix_drill_attempt_question', table_name='drill_attempts')
    op.drop_index('ix_drill_attempt_learner', table_name='drill_attempts')
    op.drop_table('drill_attempts')
    op.drop_index('ix_drill_sample', table_name='drill_questions')
    op.drop_index(op.f('ix_drill_questions_skill'), table_name='drill_questions')
    op.drop_index(op.f('ix_drill_questions_level'), table_name='drill_questions')
    op.drop_index(op.f('ix_drill_questions_kind'), table_name='drill_questions')
    op.drop_index(op.f('ix_drill_questions_exam'), table_name='drill_questions')
    op.drop_index(op.f('ix_drill_questions_canonical'), table_name='drill_questions')
    op.drop_index('ix_drill_collection_seq', table_name='drill_questions')
    op.drop_table('drill_questions')
    op.drop_index(op.f('ix_drill_collections_skill'), table_name='drill_collections')
    op.drop_index(op.f('ix_drill_collections_exam'), table_name='drill_collections')
    op.drop_index('ix_drill_collection_skill', table_name='drill_collections')
    op.drop_table('drill_collections')
    # ### end Alembic commands ###
